---
# Source: splunk-otel-collector/templates/configmap-cluster-receiver.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-k8s-cluster-receiver
  namespace: opentelemetry-operator-system
data:
  relay: |
    exporters:
      debug:
    extensions:
      health_check: null
    processors:
      batch:
        send_batch_max_size: 32768
      resource:
        attributes:
          - action: insert
            key: metric_source
            value: kubernetes
          - action: upsert
            key: k8s.cluster.name
            value: cal-otel-demo
      resource/add_collector_k8s:
        attributes:
          - action: insert
            key: k8s.node.name
            value: ${K8S_NODE_NAME}
          - action: insert
            key: k8s.pod.name
            value: ${K8S_POD_NAME}
          - action: insert
            key: k8s.pod.uid
            value: ${K8S_POD_UID}
          - action: insert
            key: k8s.namespace.name
            value: ${K8S_NAMESPACE}
      resource/k8s_cluster:
        attributes:
          - action: insert
            key: receiver
            value: k8scluster
      resourcedetection:
        detectors:
          - env
          - system
        override: true
        timeout: 15s
    receivers:
      k8s_cluster:
        auth_type: serviceAccount
      prometheus/k8s_cluster_receiver:
        config:
          scrape_configs:
            - job_name: otel-k8s-cluster-receiver
              metric_relabel_configs:
                - action: drop
                  regex: otelcol_rpc_.*
                  source_labels:
                    - __name__
                - action: drop
                  regex: otelcol_http_.*
                  source_labels:
                    - __name__
                - action: drop
                  regex: otelcol_processor_batch_.*
                  source_labels:
                    - __name__
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${K8S_POD_IP}:8889
    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          exporters:
            - debug
          processors:
            - batch
            - resource
            - resource/k8s_cluster
          receivers:
            - k8s_cluster
        metrics/collector:
          exporters:
            - debug
          processors:
            - batch
            - resource/add_collector_k8s
            - resourcedetection
            - resource
          receivers:
            - prometheus/k8s_cluster_receiver
      telemetry:
        metrics:
          address: 0.0.0.0:8889
